# Generated by Django 3.0.2 on 2022-02-04 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Support Coordinator'), ('C', 'Customer'), ('O', 'Order Coordinator')], default='U', max_length=1)),
                ('verfication_status', models.BooleanField(default=False)),
                ('registration_status', models.BooleanField(blank=True, default=False)),
                ('user_deactive_status', models.CharField(blank=True, default='', max_length=255)),
                ('user_deactive_reason', models.CharField(blank=True, default='', max_length=255)),
                ('forget_password_key', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
