# Generated by Django 3.0.2 on 2022-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
