# Generated by Django 3.0.2 on 2022-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Support Coordinator'), ('C', 'Customer'), ('O', 'Order Coordinator')], default='C', max_length=1),
        ),
    ]
