# Generated by Django 3.0.2 on 2022-02-20 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220220_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_per_page',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Paper_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Paper_type')),
                ('services_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Services_Level')),
                ('services_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Services_Type')),
            ],
        ),
    ]
