# Generated by Django 3.0.2 on 2022-02-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220220_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='Paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Paper_type'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='services_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services_Level'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='services_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services_Type'),
        ),
    ]
