# Generated by Django 3.0.2 on 2022-02-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220220_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_per_page',
        ),
        migrations.AddField(
            model_name='order',
            name='pricing',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='services.Pricing'),
        ),
    ]
