# Generated by Django 3.0.2 on 2022-02-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20220220_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='Paper_type',
        ),
        migrations.AddField(
            model_name='pricing',
            name='paper_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper_type', to='services.Paper_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='services_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_level', to='services.Services_Level'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='services_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_type', to='services.Services_Type'),
        ),
    ]
