# Generated by Django 3.0.2 on 2022-02-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220223_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services_level',
            old_name='services_name',
            new_name='services_level_name',
        ),
        migrations.RenameField(
            model_name='services_type',
            old_name='services_name',
            new_name='services_type_name',
        ),
    ]
