# Generated by Django 3.0.2 on 2022-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20220223_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='deadline',
            field=models.CharField(choices=[('2', '2 Days'), ('10', '10 Days'), ('20', '20 Days'), ('30', '30 Days')], default='2', max_length=255),
        ),
    ]
