# Generated by Django 3.0.2 on 2022-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_pricing_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('S', 'Start'), ('C', 'Completed'), ('P', 'In Process'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
