# Generated by Django 3.0.2 on 2022-03-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
