# Generated by Django 3.0.2 on 2022-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_order_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_name', models.CharField(max_length=255)),
                ('coupen_code', models.CharField(max_length=255)),
                ('coupen_fixed_price', models.CharField(blank=True, max_length=255, null=True)),
                ('coupen_percentage_price', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
